version: '3'
services:
 kafka:
  image: wurstmeister/kafka
  hostname: kafka
  environment:
   - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
  ports:
   - '9092:9092'
  depends_on:
   - zookeeper
 zookeeper:
  build: ../zookeeper
  hostname: zookeeper
  ports:
   - '2181:2181'
  